---
output:
  pdf_document: default
  html_document: default
---
# Contributions to the chapters {-}
\chaptermark{Contributions to chapters}
\setlength{\parindent}{0pt}
\small

_The contributions below were specified according to the_ CRediT _system_ [Contributor Roles Taxonomy; <https://www.casrai.org/credit.html>; @brand2015beyond].

---

**Chapter 2**, published as:

Oosterwijk, S.\*, Snoek, L.\*, Rotteveel, M., Barrett, L. F., & Scholte, H. S. (2017). Shared states: using MVPA to test neural overlap between self-focused emotion imagery and other-focused emotion understanding. *Social cognitive and affective neuroscience, 12*(7), 1025-1035.

S.O. developed the concept of the study. S.O., L.S., and H.S.S. developed the study design. L.S. and S.O. acquired the data. L.S. and S.O. analyzed the data and wrote the analysis code. S.O., L.S., and H.S.S. wrote the manuscript. M.R. and L.F.B. provided feedback on the first draft of the manuscript.

The authors would like to thank David Amodio for his helpful comments on a previous draft of this manuscript. 

**Chapter 3**, published as:

Snoek, L.\*, Miletić, S.\*, & Scholte, H.S. (2019). How to control for confounds in decoding analyses of neuroimaging data. _NeuroImage_, 184, 741-760.

L.S. and S.M. were responsible for the conceptualization, formal analysis, and development of methods. L.S., S.M., and H.S.S. wrote the manuscript. H.S.S. supervised the study.

**Chapter 4**, published as:

Snoek, L., van der Miesen, M.M., Beemsterboer, T., van der Leij, A., Eigenhuis, A., & Scholte, H.S. (2021). The Amsterdam Open MRI Collection, a set of multimodal MRI datasets for individual difference analyses. _Nature Scientific Data, 8_, 85.

L.S. curated the datasets, did visual quality control, preprocessed and analyzed the data, and wrote the article. M.v.d.M. did visual quality control, analyzed the data, and wrote the article. T.B. designed the data acquisition protocol of PIOP1 and PIOP2, was responsible for subject recruitment of PIOP1 and PIOP2, collected the data, and did visual quality control for PIOP1 and PIOP2. A.v.d.L. designed the data acquisition protocol, collected data, and did visual quality control for ID1000. A.E. designed and implemented the questionnaires in ID1000, PIOP1 and PIOP2 and managed questionnaire data from ID1000. H.S.S. was principal investigator of the ID1000, PIOP1, and PIOP2 studies, designed the data acquisition protocol of PIOP1, PIOP2, and ID1000, and wrote the article.

We thank all research assistants and students who helped collecting the data of the three projects, Jasper Wijnen and Marco Teunisse for advice and guidance with respect to anonymization and GDPR-related concerns, Jos Bloemers, Sennay Ghebreab, Adriaan Tuiten, Joram van Driel, Christian Olivers, Ilja Sligte, Sara Jahfari, Guido van Wingen, and Suzanne Oosterwijk for help with designing the paradigms, Marcus Spaan for technical support, and Franklin Feingold and Joe Wexler for help with uploading the datasets to OpenNeuro.

**Chapter 5**, published as:

Oosterwijk, S., Snoek, L., Tekoppele, J., Engelbert, L. H., & Scholte, H. S. (2020). Choosing to view morbid information involves reward circuitry. *Scientific reports, 10*(1), 1-13.

S.O., L.S., J.T., L.E. and H.S. developed the concept of the study, including the study design. S.O., L.S., J.T. and L.E. contributed to stimulus selection and programming. J.T. and L.E. collected the data. All authors contributed to the preparation of the preregistered analysis protocol and the data-analysis. S.O., L.S. and J.T. wrote the manuscript.

**Chapter 6**, submitted as:

Snoek, L., Jack, R., Schyns, P., Garrod, O., Mittenbühler, M., Scholte, H.S., & Oosterwijk, S. (submitted). Evaluating the universality of action unit based theories of categorical emotions. Submitted to *Nature Human Behavior*.

L.S., R.J., P.S., M.M., H.S.S., and S.O. were responsible for the conceptualization of the study. L.S., O.G., and M.M. developed the methods and implemented the formal analyses. All authors wrote the article.

**Chapter 7**, manuscript in preparation:

Snoek., L, Mittenbühler, M., Jack, R., Schyns, P., Fischer, A., Scholte, H.S., & Oosterwijk, S. (in prep.). Affective face perception integrates both static and dynamic information.

L.S., S.O., A.F., and H.S.S. were responsible for the conceptualization of the study. L.S. and M.M. developed the methods and implemented the formal analyses. All authors wrote the manuscript.

We thank Maite van der Miesen and Sjoerd Evelo for their help with data acquisition and Steven Miletić for helpful discussions regarding the Bayesian multivariate reverse correlation analyses.

\* Shared first authorship
