# Acknowledgments {-}
\chaptermark{Acknowledgments}

Het duurde bijna zes jaar, maar dan heb je ook wat! Een PhD doe je niet alleen en ik ben dan ook ontzettend dankbaar voor alle collega’s, vrienden, en familie waarmee ik de hoogtepunten heb kunnen vieren maar ook mijn frustraties heb kunnen delen in de afgelopen jaren.

Dit avontuur begon allemaal toen ik solliciteerde bij het Spinoza centrum, waar Steven mij toevertrouwde met een MRI scanner van anderhalf miljoen euro. Steven, je nam mij onder je hoede en leerde me niet alleen de kneepjes van *neuroimaging*, maar je begeleidde in het algemeen bij mijn “eerste stapjes” in de academische wereld. Ik deed mijn eerste onderzoeksproject en masterscriptie onder jouw (en Suzanne’s) begeleiding, maar na een mislukte beursaanvraag wist je ook nog, via via (zoals niemand anders dat kan), een PhD plek te regelen. Ik ben tot op de dag van vandaag ontiegelijk dankbaar voor deze kans. Jouw optimische kijk en oog voor “the bigger picture” waren een goede tegenhanger van mijn sceptische (en soms cynische) perspectief en mijn neiging om te vergeten waar het eigenlijk allemaal om gaat. Je hebt een lab gecreëerd waarin niet alleen goed onderzoek maar ook oog voor de mens achter de onderzoeker hoog in het vaandel staan. Bedankt voor deze fantastische periode.

Ik heb het voorrecht gehad om niet één, maar twee fantastische begeleiders te hebben gehad.  Suzanne, je bent van onmisbare waarde geweest tijdens mijn PhD en ik ben trots dat ik je eerste PhD student heb mogen zijn! Ik heb ontzettend veel van je geleerd, van ons eerste MRI project tot aan het schrijven van mijn proefschrift. Je geduld en enthousiasme om mij de ins en outs van de emotieleer bij te brengen, heb ik enorm gewaardeerd en hebben mij een betere wetenschapper gemaakt. Ook heb ik altijd genoten van onze koffiepauzes, om “even” bij te kletsen die eigenlijk altijd uitmondden in urenlange gesprekken over van alles en nog wat. Stiekem vind ik het ook wel leuk dat we het soms niet eens zijn, wat vaak leidt tot gepassioneerde discussies, waar ik altijd als een wijzer (en genuanceerder) mens uit kom. Ik hoop dat we nog vaak samen mogen werken in de toekomst!

Tomas, eigenlijk was jij een beetje mijn officieuze derde supervisor. Je hulp bij het opzetten van mijn MRI project(en) en het was fijn om iemand te hebben waar ik terecht kon voor advies over de intellectuele marteling die 7T MRI data heet. Ook zijn er maar weinig mensen waarmee ik zo ongegeneerd kan *nerden* over de nieuwste software packages, coolste analyses, en interessante artikelen. Han, ik ben dankbaar voor jouw (carrière)advies in mijn laatste jaar! Ook vond ik het leuk om samen met Claire en jou het AI vak op te zetten en een artikel te schrijven (jullie zullen elementen hiervan herkennen in de introductie van dit proefschrift!).

I’d also like to thank all members of my committee for taking the time to read and evaluate my thesis. I’m looking forward to our discussion during my defense! Dear professor Schyns, dear Philippe, I want to thank you specifically for inviting me to your lab in the summer of 2019. It was a very inspiring time and I’m looking forward to joining your lab as a post-doc this year! 

I’m happy that I have been part of the ScholteLab (spreek uit: *Sjoltie lab*) the past years. Noor, Jessica, Lynn, and our adoptees Jurriaan and Daniel &mdash; thank you for all the dinners, vrijmibos, coffee breaks, and conferences. You guys are awesome people and kick-ass scientists. Lynn, I’ve rarely met someone so humble yet so freaking smart; Jessica, you’re one of the funniest people I know and it is nice to know that there will be another neuroimaging/analysis/ML geek in the lab left after I leave. Daniel, you’re my favorite fellow Python and MRI nerd, whisky connoisseur, and Friday-afternoon-drinks buddy. Your understanding of the literature and (neuroimaging) analyses always instilled some kind of acute impostor syndrome in me, but I’m glad that I could benefit from your inexhaustible encyclopedia of knowledge. 

Also a big thank you to Room 0.03 (Josipa, Esperanza, Anderson, Max, Jurriaan, Jessica, Leon, and Lotte)! It sucks that we have seen each other so little because of Corona in the past year, but I’m grateful for the chats, coffee breaks, many cookies, and borrels over the years. The same holds of course for the rest of the Brain & Cognition group! I could not have wished for a nicer, more supportive group of colleagues. Steven (Miletić; ook wel, for some reason, “kleine Steven”), ooit was je mijn student, maar de laatste jaren kwam ik vooral naar jou voor advies. Onze “confounds” studie vond ik misschien wel het leukste project van mijn PhD. Urenlang kliederen op een whiteboard, puzzelen totdat we een ons wogen, en uiteindelijk tot een oplossing komen — wetenschap zoals ik het altijd voor me zag. Leon, ik denk niet dat je realiseert hoeveel je mij hebt geholpen met mijn proefschrift. Jouw briljante bookdown template heeft me ongetwijfeld uren aan Stackoverflow bespaard en heeft ervoor gezorgd dat mijn proefschrift er prachtig uit ziet &mdash; duizendmaal dank! Ook 

Ik heb altijd enorm genoten van het lesgeven tijdens mijn PhD. Steven en Noor (en later Jessica en Lynn), ik vond het superleuk om met jullie de neuroimaging vakken te ontwikkelen en te doceren! Ook ben ik dankbaar dat ik over de jaren zo’n leuke groep van interns heb mogen begeleiden. Cas, Andreas, Maite, Jurriaan, Lara, Max, Sjoerd, Mona, and Michelle, thank you for all your help and effort you put in our research projects. Sometimes I think that I learned more from you than the other way around.

Degenen die mij goed kennen, weten dat ik mezelf nog wel eens kan verliezen in mijn werk. Daarom ben ik blij dat ik zoveel fijne vrienden om mij heen heb die me laten zien dat er veel meer is dan alleen maar werken. Jordi, Dwin, Joost, Victor, Danny, Tom, ik ken jullie al meer dan twintig jaar. In de afgelopen twintig jaar zijn we van een volleybalteam in een klein dorpje uitgegroeid tot een hechte groep vrienden met koophuizen, baby’s, en serieuze banen. Ik geniet van elke borrel, weekendje weg, en potje volleybal/tennis/klimmen/hiken; op naar de volgende twintig jaar! Huize Commelin, het voelt nog als gisteren dat we in de woonkamer aan het Mariokarten waren. Met jullie was het altijd “work hard, play hard”, waarbij tomeloze ambitie prima kon worden afgewisseld met een festival, biertje, of lekker eten. Het wordt tijd dat Joost terug verhuist naar Nederland. The same goes for Nathaniel and Leon! I look forward to the next time we (incl. Alex of course!) are all together! Unlike before, this will probably involve strollers and diapers, though. Pol en Jorrit, we zien elkaar niet heel vaak, maar als we afspreken, dan is het feest! Ik hoop dat Jorrit snel weer met de internationale trein vanuit Limburg richting de randstad komt. Lieve besturies, het is ons tienjarige jubileum dit jaar! Wat ik ben ik blij dat ik toentertijd solliciteerde voor het ISN bestuur. Van Sevenum tot Wervershoof en van Dokkum tot Enkhuizen, wat hebben een mooie avonturen beleefd. Dat er nog veel mogen volgen!

Zoals ik al eerder schreef, is mijn wetenschappelijke avontuur begonnen bij het Spinoza centrum, welke niet zou bestaan zonder de onvolprezen Tinka. Tinka, dankjewel voor de beste bijbaan ooit! MRI vond ik hartstikke interessant enzo, maar ik vond het vooral gewoon ontzettend gezellig met jou en natuurlijk Pia, Mies, Noor, en Diane. Lieve Noor en Diane, ik ben zo blij dat jullie mijn paranimfen wilden zijn. Ook ben ik dankbaar dat jullie me af en toe achter mijn computer vandaan sleurden om te gaan borrelen, wat me oneindig veel meer waard is geweest dan dat ene extra uurtje werken. Darten in de Biergriet, Chouffe uit kartonnen bekers, Toulouse, (niet zo) stiekeme sigaretjes roken, dansen in de woonkamer &mdash; te veel mooie herinneringen om op te noemen. Keep ‘m coming.

Lieve Havertjes en aanhang, ik kan me geen leukere schoonfamilie voorstellen dan jullie! Ton en Marja, jullie hebben een fantastisch gezin, en ik ben blij dat ik daar inmiddels deel van mag uitmaken.

Jap, Claar, en Mi, het zijn een paar bewogen jaren geweest. De periode rondom het overlijden van pap was zwaar, maar ik heb veel steun aan jullie gehad en ik denk dat het ons ook dichter bij elkaar heeft gebracht. Lieve Midas, wat ben ik ook blij dat jij mijn grote kleine broertje bent! Ik geniet zo van de potjes volleybal, spelletjesmiddagen, borrels, en al dat andere leuks dat we samen doen. Je warmte, oprechte interesse, en vrolijkheid zijn de beste remedie tegen de frustratie die komt kijken bij een PhD. Anne, Midas had het niet beter kunnen treffen. Wies mag maar blij zijn met zo’n oom en tante!

Paps, wat had ik je graag mijn proefschrift willen laten zien. Ik weet zeker dat je met een groot deel het niet eens zou zijn en dat we daar dan tot in de late uren over zouden discussiëren. Dat mis ik. Die gesprekken hebben me gemaakt tot de wetenschapper die ik nu ben. Mam, de vanzelfsprekendheid waarmee je me altijd hebt gesteund, of het nou mijn sportieve of academische carrière ging, is heel bijzonder en waardeer ik tot op de dag van vandaag.

Lieve Pi, in bijna acht jaar dat we samen zijn, is er veel gebeurd, maar met jou naast me heb ik het gevoel dat ik alles aan kan. En sinds jij er bent, lieve Wies, is de wereld nog een stukje mooier.